Build a lightweight Docker image with Travis (#32)
* Update travis.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update travis.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update travis.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update travis.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update travis.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update travis.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update travis.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update travis & build script.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update travis & build script.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update travis & build script.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update travis & build script.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update travis & build script.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Forgot the dockerfile!

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Add alpine docker build.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Add alpine docker build.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update to add a fake dry-run with an empty tf file.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Markdown fix.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update links to relative path.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update to use container based (faster builds)

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Add sudo as required.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update location of scripts.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update dockerfiles. Move tests to Travis.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update terraform version in bash script.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Add support for dynamic terraform patches.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update path.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Update travis to make it verbose.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Remove unneeded Dockerfiles. Prepare to merge.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Fixes wrong tag in Docker Image.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Remove unneeded builds.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

* Fixes travis from exposing env vars.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,36 +1,58 @@
+dist: trusty
 sudo: required
 
-services:
-  - docker
+notifications:
+    email: false
 
 language: go
 go_import_path: github.com/HewlettPackard/terraform-provider-oneview
 
 go:
-- 1.8
+    - 1.8
 
 env:
-  global:
-    - REPO=dciacoe/terraform-provider-oneview
-    - TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "branch-${TRAVIS_BRANCH}"; fi)
-    - UNFORMATTED=$(find . -type f -name "*.go" -not -path "./vendor/*" | sed "s|^\./||" | xargs gofmt -l)
+    global:
+        - BUILDNAME=terraform-provider-oneview
+        - BINS_DEST=./bins
+        - CGO_ENABLED=0
+        - GOARCH=amd64
+        - REPO=$DOCKER_USERNAME/terraform-provider-oneview
+        - TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "branch-${TRAVIS_BRANCH}"; fi)
+        - UNFORMATTED=$(find . -type f -name "*.go" -not -path "./vendor/*" | sed "s|^\./||" | xargs gofmt -l)
+        - TERRAFORM_BINS=$(bash scripts/check_latest_version.sh)
 
 install:
-  - # an empty install saves the hassle of pseudo-getting deps (they're vendored, so no need!)
+    - bash scripts/download_hashicorp_bins.sh $BINS_DEST
+
+before_script:
+    - if ! [ -z "$UNFORMATTED" ]; then
+        echo -e "Go files must be formatted with gofmt. Please run:";
+        for fn in $UNFORMATTED; do
+        echo -e "  gofmt -w $PWD/$fn";
+        done;
+        exit 1;
+      fi
 
 script:
-  - if ! [ -z "$UNFORMATTED" ]; then
-      echo -e "Go files must be formatted with gofmt. Please run:";
-      for fn in $UNFORMATTED; do
-        echo -e "  gofmt -w $PWD/$fn";
-      done;
-      exit 1;
-    fi
-  - go vet $(go list ./... | grep -v '/vendor/')
-  - go test -v $(go list ./... | grep -v '/vendor/')
-  - docker build -f Dockerfile -t $REPO:$TAG .
-  - docker run -it --rm=true $REPO:$TAG /bin/ash -c "echo '' >> /demo.tf && cd / && /usr/local/terraform/terraform plan"
+    # Standard Go testing avoiding the testing of the vendor folder.
+    - go vet $(go list ./... | grep -v '/vendor/')
+    - go test -v $(go list ./... | grep -v '/vendor/')
+
+    # Build for Windows, Mac and Linux disabling CGO and getting a statically
+    # linked binary.
+    - GOOS=linux go build -a -tags netgo -ldflags '-s -w' -o $BINS_DEST/linux/$BUILDNAME
+    # - GOOS=windows go build -a -tags netgo -ldflags '-s -w' -o $BINS_DEST/windows/$BUILDNAME.exe  # disabled until next iteration
+    # - GOOS=darwin go build -a -tags netgo -ldflags '-s -w' -o $BINS_DEST/macos/$BUILDNAME         # disabled until next iteration
+
+    # Create the docker image from the Dockerfile.
+    - docker build -f Dockerfile -t $REPO:$TAG .
+
+    # Run a Sanity Check against an empty terraform file. When
+    # ran, it should fail if the compilation was unsuccessful.
+    - docker run -it --rm=true $REPO:$TAG /bin/ash -c "echo '' >> /demo.tf && cd / && /usr/local/terraform/terraform plan"
 
 after_success:
-  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
-  - docker push $REPO
+    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
+        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
+        docker push $REPO;
+      fi
